/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { StartWorkflow } from '../models/StartWorkflow';
import { TaskDetails } from '../models/TaskDetails';
import { HttpFile } from '../http/http';

export class Action {
    'action'?: ActionActionEnum;
    'startWorkflow'?: StartWorkflow;
    'completeTask'?: TaskDetails;
    'failTask'?: TaskDetails;
    'expandInlineJSON'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "action",
            "baseName": "action",
            "type": "ActionActionEnum",
            "format": ""
        },
        {
            "name": "startWorkflow",
            "baseName": "start_workflow",
            "type": "StartWorkflow",
            "format": ""
        },
        {
            "name": "completeTask",
            "baseName": "complete_task",
            "type": "TaskDetails",
            "format": ""
        },
        {
            "name": "failTask",
            "baseName": "fail_task",
            "type": "TaskDetails",
            "format": ""
        },
        {
            "name": "expandInlineJSON",
            "baseName": "expandInlineJSON",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Action.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ActionActionEnum {
    StartWorkflow = 'start_workflow',
    CompleteTask = 'complete_task',
    FailTask = 'fail_task'
}

