/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class BulkResponse {
    'bulkErrorResults'?: { [key: string]: string; };
    'bulkSuccessfulResults'?: Array<string>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "bulkErrorResults",
            "baseName": "bulkErrorResults",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "bulkSuccessfulResults",
            "baseName": "bulkSuccessfulResults",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return BulkResponse.attributeTypeMap;
    }

    public constructor() {
    }
}

