/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Health } from '../models/Health';
import { HttpFile } from '../http/http';

export class HealthCheckStatus {
    'healthResults'?: Array<Health>;
    'suppressedHealthResults'?: Array<Health>;
    'healthy'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "healthResults",
            "baseName": "healthResults",
            "type": "Array<Health>",
            "format": ""
        },
        {
            "name": "suppressedHealthResults",
            "baseName": "suppressedHealthResults",
            "type": "Array<Health>",
            "format": ""
        },
        {
            "name": "healthy",
            "baseName": "healthy",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return HealthCheckStatus.attributeTypeMap;
    }

    public constructor() {
    }
}

