/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class PollData {
    'queueName'?: string;
    'domain'?: string;
    'workerId'?: string;
    'lastPollTime'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "queueName",
            "baseName": "queueName",
            "type": "string",
            "format": ""
        },
        {
            "name": "domain",
            "baseName": "domain",
            "type": "string",
            "format": ""
        },
        {
            "name": "workerId",
            "baseName": "workerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastPollTime",
            "baseName": "lastPollTime",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return PollData.attributeTypeMap;
    }

    public constructor() {
    }
}

