/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class RerunWorkflowRequest {
    'reRunFromWorkflowId'?: string;
    'workflowInput'?: { [key: string]: any; };
    'reRunFromTaskId'?: string;
    'taskInput'?: { [key: string]: any; };
    'correlationId'?: string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reRunFromWorkflowId",
            "baseName": "reRunFromWorkflowId",
            "type": "string",
            "format": ""
        },
        {
            "name": "workflowInput",
            "baseName": "workflowInput",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "reRunFromTaskId",
            "baseName": "reRunFromTaskId",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskInput",
            "baseName": "taskInput",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "correlationId",
            "baseName": "correlationId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return RerunWorkflowRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

