/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Workflow } from '../models/Workflow';
import { HttpFile } from '../http/http';

export class SearchResultWorkflow {
    'totalHits'?: number;
    'results'?: Array<Workflow>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "totalHits",
            "baseName": "totalHits",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "results",
            "baseName": "results",
            "type": "Array<Workflow>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SearchResultWorkflow.attributeTypeMap;
    }

    public constructor() {
    }
}

