/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SkipTaskRequest {
    'taskInput'?: { [key: string]: any; };
    'taskOutput'?: { [key: string]: any; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "taskInput",
            "baseName": "taskInput",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "taskOutput",
            "baseName": "taskOutput",
            "type": "{ [key: string]: any; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SkipTaskRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

