/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { WorkflowDef } from '../models/WorkflowDef';
import { HttpFile } from '../http/http';

export class SubWorkflowParams {
    'name': string;
    'version'?: number;
    'taskToDomain'?: { [key: string]: string; };
    'workflowDefinition'?: WorkflowDef;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "taskToDomain",
            "baseName": "taskToDomain",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "workflowDefinition",
            "baseName": "workflowDefinition",
            "type": "WorkflowDef",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SubWorkflowParams.attributeTypeMap;
    }

    public constructor() {
    }
}

