/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskExecLog } from '../models/TaskExecLog';
import { HttpFile } from '../http/http';

export class TaskResult {
    'workflowInstanceId': string;
    'taskId': string;
    'reasonForIncompletion'?: string;
    'callbackAfterSeconds'?: number;
    'workerId'?: string;
    'status'?: TaskResultStatusEnum;
    'outputData'?: { [key: string]: any; };
    'logs'?: Array<TaskExecLog>;
    'externalOutputPayloadStoragePath'?: string;
    'subWorkflowId'?: string;
    'extendLease'?: boolean;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "workflowInstanceId",
            "baseName": "workflowInstanceId",
            "type": "string",
            "format": ""
        },
        {
            "name": "taskId",
            "baseName": "taskId",
            "type": "string",
            "format": ""
        },
        {
            "name": "reasonForIncompletion",
            "baseName": "reasonForIncompletion",
            "type": "string",
            "format": ""
        },
        {
            "name": "callbackAfterSeconds",
            "baseName": "callbackAfterSeconds",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "workerId",
            "baseName": "workerId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskResultStatusEnum",
            "format": ""
        },
        {
            "name": "outputData",
            "baseName": "outputData",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "logs",
            "baseName": "logs",
            "type": "Array<TaskExecLog>",
            "format": ""
        },
        {
            "name": "externalOutputPayloadStoragePath",
            "baseName": "externalOutputPayloadStoragePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "subWorkflowId",
            "baseName": "subWorkflowId",
            "type": "string",
            "format": ""
        },
        {
            "name": "extendLease",
            "baseName": "extendLease",
            "type": "boolean",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return TaskResult.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskResultStatusEnum {
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    FailedWithTerminalError = 'FAILED_WITH_TERMINAL_ERROR',
    Completed = 'COMPLETED'
}

