/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class TaskMock {
    'status'?: TaskMockStatusEnum;
    'output'?: { [key: string]: any; };
    'executionTime'?: number;
    'queueWaitTime'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "TaskMockStatusEnum",
            "format": ""
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "executionTime",
            "baseName": "executionTime",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "queueWaitTime",
            "baseName": "queueWaitTime",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return TaskMock.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum TaskMockStatusEnum {
    InProgress = 'IN_PROGRESS',
    Failed = 'FAILED',
    FailedWithTerminalError = 'FAILED_WITH_TERMINAL_ERROR',
    Completed = 'COMPLETED'
}

