/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { TaskMock } from '../models/TaskMock';
import { WorkflowDef } from '../models/WorkflowDef';
import { HttpFile } from '../http/http';

export class WorkflowTestRequest {
    'name': string;
    'version'?: number;
    'correlationId'?: string;
    'input'?: { [key: string]: any; };
    'taskToDomain'?: { [key: string]: string; };
    'workflowDef'?: WorkflowDef;
    'externalInputPayloadStoragePath'?: string;
    'priority'?: number;
    'taskRefToMockOutput'?: { [key: string]: Array<TaskMock>; };
    'subWorkflowTestRequest'?: { [key: string]: WorkflowTestRequest; };

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "correlationId",
            "baseName": "correlationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "{ [key: string]: any; }",
            "format": ""
        },
        {
            "name": "taskToDomain",
            "baseName": "taskToDomain",
            "type": "{ [key: string]: string; }",
            "format": ""
        },
        {
            "name": "workflowDef",
            "baseName": "workflowDef",
            "type": "WorkflowDef",
            "format": ""
        },
        {
            "name": "externalInputPayloadStoragePath",
            "baseName": "externalInputPayloadStoragePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "taskRefToMockOutput",
            "baseName": "taskRefToMockOutput",
            "type": "{ [key: string]: Array<TaskMock>; }",
            "format": ""
        },
        {
            "name": "subWorkflowTestRequest",
            "baseName": "subWorkflowTestRequest",
            "type": "{ [key: string]: WorkflowTestRequest; }",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return WorkflowTestRequest.attributeTypeMap;
    }

    public constructor() {
    }
}

