/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class WorkflowSummary {
    'workflowType'?: string;
    'version'?: number;
    'workflowId'?: string;
    'correlationId'?: string;
    'startTime'?: string;
    'updateTime'?: string;
    'endTime'?: string;
    'status'?: WorkflowSummaryStatusEnum;
    'input'?: string;
    'output'?: string;
    'reasonForIncompletion'?: string;
    'executionTime'?: number;
    'event'?: string;
    'failedReferenceTaskNames'?: string;
    'externalInputPayloadStoragePath'?: string;
    'externalOutputPayloadStoragePath'?: string;
    'priority'?: number;
    'failedTaskNames'?: Set<string>;
    'inputSize'?: number;
    'outputSize'?: number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "workflowType",
            "baseName": "workflowType",
            "type": "string",
            "format": ""
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "workflowId",
            "baseName": "workflowId",
            "type": "string",
            "format": ""
        },
        {
            "name": "correlationId",
            "baseName": "correlationId",
            "type": "string",
            "format": ""
        },
        {
            "name": "startTime",
            "baseName": "startTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "updateTime",
            "baseName": "updateTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "endTime",
            "baseName": "endTime",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "WorkflowSummaryStatusEnum",
            "format": ""
        },
        {
            "name": "input",
            "baseName": "input",
            "type": "string",
            "format": ""
        },
        {
            "name": "output",
            "baseName": "output",
            "type": "string",
            "format": ""
        },
        {
            "name": "reasonForIncompletion",
            "baseName": "reasonForIncompletion",
            "type": "string",
            "format": ""
        },
        {
            "name": "executionTime",
            "baseName": "executionTime",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "event",
            "baseName": "event",
            "type": "string",
            "format": ""
        },
        {
            "name": "failedReferenceTaskNames",
            "baseName": "failedReferenceTaskNames",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalInputPayloadStoragePath",
            "baseName": "externalInputPayloadStoragePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "externalOutputPayloadStoragePath",
            "baseName": "externalOutputPayloadStoragePath",
            "type": "string",
            "format": ""
        },
        {
            "name": "priority",
            "baseName": "priority",
            "type": "number",
            "format": "int32"
        },
        {
            "name": "failedTaskNames",
            "baseName": "failedTaskNames",
            "type": "Set<string>",
            "format": ""
        },
        {
            "name": "inputSize",
            "baseName": "inputSize",
            "type": "number",
            "format": "int64"
        },
        {
            "name": "outputSize",
            "baseName": "outputSize",
            "type": "number",
            "format": "int64"
        }    ];

    static getAttributeTypeMap() {
        return WorkflowSummary.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum WorkflowSummaryStatusEnum {
    Running = 'RUNNING',
    Completed = 'COMPLETED',
    Failed = 'FAILED',
    TimedOut = 'TIMED_OUT',
    Terminated = 'TERMINATED',
    Paused = 'PAUSED'
}

